In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

#    Q1.  A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.



# here we will do the 2 tail t -test
# null hypothesis : mu1=mu2, Alternative Hypothesis: mu1≠mu2
# significance level is alpha=0.05

In [2]:
#importing the dataset
data= pd.read_csv("cutlets.csv")
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
#applying the 2 tail t-test
stats.ttest_ind(data['Unit A'],data['Unit B'])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

# Since pvalue > alpha therefore we accept the null hypothesis.There is no  significant difference in the diameter of the cutlet between two units. 

# Q2. A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.


# Here We are going to conduct a ANOVA Test on 4 Independent samples with Numerical Data.
# Null Hypothesis: mu1=mu2=mu3=mu3
# Alternative Hypothesis: Atleast one is different.
# Significance 

In [4]:
#importing the dataset
data2=pd.read_csv("LabTAT.csv")
data2.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [5]:
#ANOVA test
stats.f_oneway(data2.iloc[:,0],data2.iloc[:,1],data2.iloc[:,2],data2.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

# since p_value>Alpha therefore we accept the null hypothes.There is no difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list.

# Q3. Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions


# We are going to conduct a Test of Independence using Chi-Square  test with Contingency table
# Null Hypothesis:no association or dependency between the gender based buyer rations across regions.
# Alternative Hypothesis:There is a significant association or dependency between the gender based buyer rations across regions
# Significance level: Alpha=0.05


In [12]:
from scipy.stats import chi2_contingency

In [13]:
data3=pd.read_csv("BuyerRatio.csv")
data3.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [14]:
data3=data3.drop(['Observed Values'], axis=1,)
data3

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [19]:
obs=[[50,142,131,70],[435,1523,1356,750]]

In [18]:
# Applying the chi-square contingency table to convert observed value into expected value
stat, p, dof, exp= stats.chi2_contingency(data3)
exp

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [20]:
stats.chi2_contingency(obs)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [21]:
observed=np.array([50,142,131,70,435,1523,1356,750])
expected= np.array([42.76531299,  146.81287862,  131.11756787,   72.30424052,
       442.23468701, 1518.18712138, 1355.88243213,  747.69575948])

In [22]:
stats.chisquare(observed,expected,ddof=3)

Power_divergenceResult(statistic=1.5959455390914483, pvalue=0.8095206646905712)

# p_value> alpha value therefore we accept null hypothesis. Therefore, there is no association or dependency between male-female buyers rations and are similar across regions.

# Q4. TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

# We are going to conduct a Test of Independence using Chi-Square  test with Contingency table
# Null Hypothesis: mu1=mu2=mu3=mu4
# Alternative Hypthosis: Atleast One of them is Differente
# significance : alpha=0.05

In [23]:
#importing the dataset
data4=pd.read_csv("Costomer+OrderForm.csv")
data4.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [24]:
data4['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [25]:
data4['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [26]:
data4['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [27]:
data4['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [28]:
contingency_table= [[271,267,269,280],[29,33,31,20]]
contingency_table

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [34]:
#calculating the expected values
stat, p, df, exp = stats.chi2_contingency(contingency_table)
exp

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [30]:
# defining the expected values and observed values
observed= np.array([271,267,269,280,29,33,31,20])
expected=np.array([271.75, 271.75, 271.75, 271.75
        , 28.25,  28.25,  28.25,  28.25])

In [35]:
stats.chisquare(observed,expected,ddof=df)

Power_divergenceResult(statistic=3.858960685820355, pvalue=0.4254298144535761)

# p_value > alpha value therefore we accept the null hypothesis